name = "astro-blog"
compatibility_date = "2024-01-01"

# Pages 项目配置
pages_build_output_dir = "dist"

# 如果需要设置环境变量，可以在这里添加
# [vars]
# MY_VARIABLE = "production-value"

# 生产环境配置
[env.production]
# 生产环境变量

# 预览环境配置
[env.preview]
# 预览环境变量
